# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpPoMu8xI56VmKLdcOT9ppbj4poJW7WW
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
import joblib

# --- 1. Page Configuration ---
st.set_page_config(
    page_title="FORACCA: Climate Sentinel",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. Data Loading (Cached for Performance) ---
@st.cache_resource
def load_assets():
    # Ensure these files are in the same folder as app.py
    df = pd.read_parquet('Armenia_ML_Training_Data.parquet')
    border = gpd.read_file('arm_admin0.geojson')
    model = joblib.load('RF_FVS_Model.joblib')
    return df, border, model

try:
    df_forest, armenia_border, rf_model = load_assets()
except Exception as e:
    st.error(f"Error loading data files. Ensure they are in the same directory. Details: {e}")
    st.stop()

# Training range constraints
vmax_vpd = df_forest['Delta_VPD_GS'].quantile(0.99)
vmax_temp = df_forest['Delta_Tmax_GS'].quantile(0.99)
vmin_prec = df_forest['Delta_P_GS'].quantile(0.01)

# Projection Matrix
projection_matrix = {
    'Medium-Term (2041–2060)': {
        'ssp126': (1.3, 14.24, 0.058),
        'ssp245': (1.5, -9.48, 0.068),
        'ssp370': (1.8, -45.81, 0.082),
        'ssp585': (2.3, 1.36, 0.106)
    },
    'Long-Term (2081–2100)': {
        'ssp126': (1.3, 17.12, 0.058),
        'ssp245': (2.4, 6.88, 0.111),
        'ssp370': (3.8, -81.32, 0.184),
        'ssp585': (5.2, -5.11, 0.262)
    }
}

# --- 3. Sidebar UI ---
st.sidebar.title("🌲 Model Controls")
mode = st.sidebar.selectbox(
    "Operation Mode",
    options=['Historical Baseline', 'IPCC Scenarios', 'Custom Forcing'],
    index=0
)

# Dynamic Metric Selection
metric_options = [('Canopy Structure [σ(H)]', 'sigma')]
if mode != 'Historical Baseline':
    metric_options = [('Forest Vulnerability Score [FVS]', 'fvs')] + metric_options

metric = st.sidebar.selectbox("Metric to Display", options=metric_options, format_func=lambda x: x[0])[1]

dt, dp, dv = 0.0, 0.0, 0.0

if mode == 'IPCC Scenarios':
    period = st.sidebar.selectbox("Time Horizon", options=list(projection_matrix.keys()))
    ssp = st.sidebar.radio("Pathway (SSP)", options=['ssp126', 'ssp245', 'ssp370', 'ssp585'],
                           format_func=lambda x: x.upper().replace('SSP', 'SSP '))
    dt, dp, dv = projection_matrix[period][ssp]

elif mode == 'Custom Forcing':
    st.sidebar.markdown("---")
    st.sidebar.subheader("Custom Climate Variables")
    dt = st.sidebar.slider('Δ Tmax (°C)', 0.0, 6.0, 0.0, 0.1)
    dp = st.sidebar.slider('Δ Prec (mm)', -150, 100, 0, 1)
    dv = st.sidebar.slider('Δ VPD (kPa)', 0.0, 1.0, 0.0, 0.01)

# --- 4. Logic Engine & Prediction ---
if mode == 'Historical Baseline':
    y_vals = df_forest['vhm_std']
    title = "Historical Baseline"
    subtitle = "(1979-2018 Observational Data)"
    vmin, vmax, cmap, unit = 0, 8, 'RdYlGn', "meters"
else:
    # Predictive Calculation
    X_in = pd.DataFrame({
        'Delta_VPD_GS': (df_forest['Delta_VPD_GS'] + dv).clip(upper=vmax_vpd),
        'Delta_Tmax_GS': (df_forest['Delta_Tmax_GS'] + dt).clip(upper=vmax_temp),
        'Delta_P_GS': (df_forest['Delta_P_GS'] + dp).clip(lower=vmin_prec)
    })
    y_pred = rf_model.predict(X_in)

    if metric == 'fvs':
        y_vals = ((df_forest['vhm_std'] - y_pred) / df_forest['vhm_std'] * 100).clip(0, 100)
        title, vmin, vmax, cmap, unit = "Forest Vulnerability Score (FVS)", 0, 80, 'YlOrRd', "Index"
    else:
        y_vals = y_pred
        title, vmin, vmax, cmap, unit = "Projected Canopy Structure [σ(H)]", 0, 8, 'RdYlGn', "meters"

    subtitle = f"{period if mode == 'IPCC' else 'Custom Scenario'}\nΔTmax: +{dt}°C | ΔPrec: {dp}mm | ΔVPD: +{dv}kPa"

# --- 5. Main Dashboard Display ---
st.markdown(f"<h1 style='color:#1b5e20;'>FORACCA: Temporal Climate Sentinel</h1>", unsafe_allow_html=True)
st.subheader(f"{title}")
st.write(subtitle)

# Metrics Summary
col1, col2, col3 = st.columns(3)
col1.metric("Mean Value", f"{y_vals.mean():.2f} {unit}")
col2.metric("Min", f"{y_vals.min():.2f}")
col3.metric("Max", f"{y_vals.max():.2f}")

# Plotting
fig, ax = plt.subplots(figsize=(12, 7), facecolor='none')
armenia_border.plot(ax=ax, color='#eeeeee', edgecolor='#bcbcbc')
sc = ax.scatter(df_forest['x'], df_forest['y'], c=y_vals, cmap=cmap, s=15, vmin=vmin, vmax=vmax, zorder=2)
plt.colorbar(sc, label=unit, fraction=0.03, pad=0.01)
ax.axis('off')

st.pyplot(fig)