# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpPoMu8xI56VmKLdcOT9ppbj4poJW7WW
"""
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
import joblib

# --- 1. Page Configuration ---
st.set_page_config(
    page_title="FORACCA: Climate Sentinel",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. Data Loading (Cached) ---
@st.cache_resource
def load_assets():
    df = pd.read_parquet('Armenia_ML_Training_Data.parquet')
    border = gpd.read_file('arm_admin0.geojson')
    model = joblib.load('RF_FVS_Model.joblib')
    return df, border, model

try:
    df_forest, armenia_border, rf_model = load_assets()
except Exception as e:
    st.error(f"Error loading data files: {e}")
    st.stop()

# Constraints & Mapping
vmax_vpd = df_forest['Delta_VPD_GS'].quantile(0.99)
vmax_temp = df_forest['Delta_Tmax_GS'].quantile(0.99)
vmin_prec = df_forest['Delta_P_GS'].quantile(0.01)

ssp_mapping = {
    'ssp126': 'SSP1-2.6',
    'ssp245': 'SSP2-4.5',
    'ssp370': 'SSP3-7.0',
    'ssp585': 'SSP5-8.5'
}

projection_matrix = {
    'Medium-Term (2041–2060)': {
        'ssp126': (1.3, 14.24, 0.058), 'ssp245': (1.5, -9.48, 0.068),
        'ssp370': (1.8, -45.81, 0.082), 'ssp585': (2.3, 1.36, 0.106)
    },
    'Long-Term (2081–2100)': {
        'ssp126': (1.3, 17.12, 0.058), 'ssp245': (2.4, 6.88, 0.111),
        'ssp370': (3.8, -81.32, 0.184), 'ssp585': (5.2, -5.11, 0.262)
    }
}

# --- 3. Sidebar UI ---
st.sidebar.title("🌲 Model Controls")
mode = st.sidebar.selectbox("Operation Mode", ['Historical Baseline', 'IPCC Scenarios', 'Custom Forcing'])

metric_options = [('Canopy Structure [σ(H)]', 'sigma')]
if mode != 'Historical Baseline':
    metric_options = [('Forest Vulnerability Score [FVS]', 'fvs')] + metric_options

metric = st.sidebar.selectbox("Metric", options=metric_options, format_func=lambda x: x[0])[1]

dt, dp, dv = 0.0, 0.0, 0.0
if mode == 'IPCC Scenarios':
    period = st.sidebar.selectbox("Time Horizon", options=list(projection_matrix.keys()))
    ssp_key = st.sidebar.radio("Pathway (SSP)", options=list(ssp_mapping.keys()), 
                               format_func=lambda x: ssp_mapping[x])
    dt, dp, dv = projection_matrix[period][ssp_key]
elif mode == 'Custom Forcing':
    dt = st.sidebar.slider('Δ Tmax (°C)', 0.0, 6.0, 0.0, 0.1)
    dp = st.sidebar.slider('Δ Prec (mm)', -150, 100, 0, 1)
    dv = st.sidebar.slider('Δ VPD (kPa)', 0.0, 1.0, 0.0, 0.01)

# --- 4. Predictive Engine ---
if mode == 'Historical Baseline':
    y_vals = df_forest['vhm_std']
    title, subtitle = "Historical Baseline", "(1979-2018 Observational Data)"
    vmin, vmax, cmap, unit = 0, 8, 'RdYlGn', "meters"
else:
    X_in = pd.DataFrame({
        'Delta_VPD_GS': (df_forest['Delta_VPD_GS'] + dv).clip(upper=vmax_vpd),
        'Delta_Tmax_GS': (df_forest['Delta_Tmax_GS'] + dt).clip(upper=vmax_temp),
        'Delta_P_GS': (df_forest['Delta_P_GS'] + dp).clip(lower=vmin_prec)
    })
    y_pred = rf_model.predict(X_in)
    
    if metric == 'fvs':
        y_vals = ((df_forest['vhm_std'] - y_pred) / df_forest['vhm_std'] * 100).clip(0, 100)
        title, vmin, vmax, cmap, unit = "Forest Vulnerability Score (FVS)", 0, 80, 'YlOrRd', "Index"
    else:
        y_vals = y_pred
        title, vmin, vmax, cmap, unit = "Projected Canopy Structure [σ(H)]", 0, 8, 'RdYlGn', "meters"
    
    label = f"IPCC Scenario ({period} | {ssp_mapping[ssp_key]})" if mode == 'IPCC Scenarios' else "Custom Scenario"
    subtitle = f"{label} | ΔTmax: +{dt}°C | ΔPrec: {dp}mm | ΔVPD: +{dv}kPa"

# --- 5. Display ---
st.markdown(f"<h2 style='color:#1b5e20;'>Predictive Framework for Climate-Smart Reforestation</h2><br><p style='margin-top:-10px;'><i>Validated Modeling for Armenia's Forest Resilience</i></p>", unsafe_allow_html=True)
st.subheader(title)
st.write(subtitle)
fig, ax = plt.subplots(figsize=(10, 6), facecolor='none')
armenia_border.plot(ax=ax, color='#eeeeee', edgecolor='#bcbcbc')
sc = ax.scatter(df_forest['x'], df_forest['y'], c=y_vals, cmap=cmap, s=15, vmin=vmin, vmax=vmax)
plt.colorbar(sc, label=unit)
ax.axis('off')
st.pyplot(fig)
